---
name: Feature Request
description: Suggest a new feature for the OJS Java SDK
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please fill out the information below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Include API examples if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Client (OJSClient)
        - Worker (OJSWorker)
        - Workflows
        - Transport
        - Error Handling
        - Testing
        - Documentation
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references (e.g., OJS spec sections).
